[package]
name = "perg"
version = "0.1.0"
authors = ["Vinh Nguyen <vinhnguyen2308@gmail.com>"]
license = "MIT"
description = "A tool to search files"
readme = "README.md"
homepage = "https://github.com/vinhnx/perg"
repository = "https://github.com/vinhnx/perg"
keywords = ["cli", "search", "demo"]
categories = ["command-line-utilities"]

[dependencies]
exitfailure = "0.5.1"
structopt = "0.2.10"
assert_cmd = "0.10"
predicates = "1"
tempfile = "3"