[package]
name = "perg"
version = "0.4.0"
authors = ["Vinh Nguyen <vinhnguyen2308@gmail.com>"]
license = "MIT"
description = "perg is a small command-line tool to search for given string inside a file"
readme = "README.md"
homepage = "https://github.com/vinhnx/perg"
repository = "https://github.com/vinhnx/perg"
keywords = ["cli", "search"]
categories = ["command-line-utilities"]

[dependencies]
predicates = "1.0.0"
regex = "1.1.6"
clap = "2.33.0"
